server:
  port: 9393
  error:
    include-stacktrace: never

spring:
  application:
    name: api-vollmed
  web:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/vollmed
    username: vollmed
    password: vollmed
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml